document.writeln('<div align="center">');
document.writeln('<script type="text/javascript"><!--');
document.writeln('google_ad_client="pub-5814409658542983";');
document.writeln('google_ad_host="pub-0720175472434865";');
document.writeln('google_ad_width=468;');
document.writeln('google_ad_height=60;');
document.writeln('google_ad_format="468x60_as";');
document.writeln('google_ad_type="text_image";');
document.writeln('google_ad_channel="3699102132";');
document.writeln('google_color_border="FFFFFF";');
document.writeln('google_color_bg="FFFFFF";');
document.writeln('google_color_link="0000FF";');
document.writeln('google_color_url="008000";');
document.writeln('google_color_text="000000";');
document.writeln('//--></script>');
document.writeln('<script type="text/javascript"');
document.writeln('  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">');
document.writeln('</script>');
document.writeln('</div>');
